### ISSUE TITLE
Cant get version 1.3.9 to load on Vs Code

### ISSUE THREAD

**Issue by kungjohan** [bneumann/CppUTest-Test-Adapter#65]
Tested version 1.3.9 on Vs code both on Windows and MacOS. It seems like the plugin does not load and on runtime status it says not activate. After a lot of fiddling and configuring I tried to downgrade to previous release 1.3.4 and it loads as expected.

If there are any logging or so I could do I would be eager to help. But I dont know how to debug this.

**Comment by bneumann** [comment]
Hey, there is some logging, this can be done by setting the `cpputestTestAdapter.logpanel` property to true. And after that you should see the logs here:

![grafik](https://github.com/user-attachments/assets/0199e627-468b-4b2f-a826-627bba2ee1a3)


Unfortunately I can not reproduce it here, you can also give me your testrunner binary (for windows), if you are allowed to, so I can check out what's going wrong.

I guess  you didn't change anything in your setup or your files right? Because in #26 someone also has problems during loading, which seems weird as it should work

**Comment by bneumann** [comment]
I just recreated my environment in WSL and it looks like I get the same error as you now. Will investigate

**Comment by kungjohan** [comment]
Tried this on MacOs. on 1.3.4 I get logfile on output. But on latest 1.3.9 It says not activated. Found the below in log

2024-10-06 14:22:57.041 [info] ExtensionService#_doActivateExtension bneumann.cpputest-test-adapter, startup: false, activationEvent: 'onStartupFinished'
2024-10-06 14:22:57.043 [error] Activating extension bneumann.cpputest-test-adapter failed due to an error:
2024-10-06 14:22:57.043 [error] Error: Cannot find module 'vscode-test-adapter-api'
Require stack:
- /Users/johan/.vscode/extensions/bneumann.cpputest-test-adapter-1.3.9/out/main.js
- /private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2786)
	at Module._load (node:internal/modules/cjs/loader:974:27)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
	at n._load (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
	at t._load (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/Users/johan/.vscode/extensions/bneumann.cpputest-test-adapter-1.3.9/out/main.js:5:35)
	at o._compile (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
	at n._load (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
	at t._load (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:98)
	at f.vb (/private/var/folders/fz/lq25k53s0fjgc0m2db5fyjv80000gn/T/AppTranslocation/A53B01CC-3D7B-440A-8997-204FE03EAB31/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:30730)
	at async Promise.all (index 0)
2024-10-06 14:22:57.043 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'

**Comment by kungjohan** [comment]
Tested the new version 1.3.10 but unfortenately I cant get it to work

2024-10-06 20:01:26.943 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-10-06 20:01:26.952 [info] ExtensionService#_doActivateExtension bneumann.cpputest-test-adapter, startup: false, activationEvent: 'onStartupFinished'
2024-10-06 20:01:26.955 [error] Activating extension bneumann.cpputest-test-adapter failed due to an error:
2024-10-06 20:01:26.955 [error] Error: Cannot find module 'vscode-test-adapter-api'
Require stack:
- /Users/johan/.vscode/extensions/bneumann.cpputest-test-adapter-1.3.10/out/main.js
- /Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
	at i._resolveFilename (node:electron/js2c/utility_init:2:13739)
	at t._resolveFilename (file:///Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22704)
	at Module._load (node:internal/modules/cjs/loader:993:27)
	at c._load (node:electron/js2c/node_init:2:13801)
	at e._load (file:///Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (/Users/johan/.vscode/extensions/bneumann.cpputest-test-adapter-1.3.10/out/main.js:5:35)
	at Module._compile (node:internal/modules/cjs/loader:1373:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at e._load (file:///Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at hB.xb (file:///Applications/Visual%20Studio%20Code%202.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23767)
	at async Promise.all (index 0)

**Comment by bneumann** [comment]
Hmm that is so weird. Can you, just for testing, install this extension here please:
https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer

it is the legacy explorer I was building upon initially, which I tried to remove. Unsuccessfully.

**Comment by kungjohan** [comment]
It seem like I have v2.22.1 of the test explorer installed on my MacOs computer and still it does not work. Will test with windows at work today and see if there are any differences.

**Comment by bneumann** [comment]
It gets weirded by the minute. I have readded the dependency and actually I only use the API wrapper of the legacy test engine which is not found in your installation. I will setup a clean vanilla VSCode for testing to see what's happening

**Comment by kungjohan** [comment]
I can verify 1.3.11 works for me. Thanks for the good support!
